"""Initial migration.

Revision ID: 88e783eb7ad8
Revises: 
Create Date: 2024-12-06 19:14:36.070212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e783eb7ad8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('cp', sa.Integer(), nullable=False),
    sa.Column('trestbps', sa.Integer(), nullable=False),
    sa.Column('chol', sa.Integer(), nullable=False),
    sa.Column('fbs', sa.Integer(), nullable=False),
    sa.Column('restecg', sa.Integer(), nullable=False),
    sa.Column('thalach', sa.Integer(), nullable=False),
    sa.Column('exang', sa.Integer(), nullable=False),
    sa.Column('oldpeak', sa.Float(), nullable=False),
    sa.Column('slope', sa.Integer(), nullable=False),
    sa.Column('ca', sa.Integer(), nullable=False),
    sa.Column('thal', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_table')
    # ### end Alembic commands ###
