"""Initial migration.

Revision ID: a0b7a1a1173c
Revises: 88e783eb7ad8
Create Date: 2024-12-09 21:16:19.615814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b7a1a1173c'
down_revision = '88e783eb7ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('message', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_column('oldpeak')
        batch_op.drop_column('ca')
        batch_op.drop_column('thal')
        batch_op.drop_column('exang')
        batch_op.drop_column('thalach')
        batch_op.drop_column('age')
        batch_op.drop_column('target')
        batch_op.drop_column('slope')
        batch_op.drop_column('fbs')
        batch_op.drop_column('restecg')
        batch_op.drop_column('cp')
        batch_op.drop_column('chol')
        batch_op.drop_column('sex')
        batch_op.drop_column('trestbps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trestbps', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('sex', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('chol', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('cp', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('restecg', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('fbs', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('slope', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('target', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('thalach', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('exang', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('thal', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('ca', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('oldpeak', sa.FLOAT(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('message')
        batch_op.drop_column('subject')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
