name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print environment variables 
        run: | 
          echo "GITHUB_URL=${{ secrets.MAIN_GITHUB_URL }}" 
          echo "MEDIUM_URL=${{ secrets.MAIN_MEDIUM_URL }}" 
          echo "LINKEDIN_URL=${{ secrets.MAIN_LINKEDIN_URL }}" 
          echo "TWITTER_URL=${{ secrets.MAIN_TWITTER_URL }}" 
          echo "SECRET_KEY=${{ secrets.MAIN_SECRET_KEY }}" 
          echo "SQLALCHEMY_TRACK_MODIFICATIONS=${{ secrets.MAIN_SQLALCHEMY_TRACK_MODIFICATIONS }}" 
          echo "FLASK_CONFIG=${{ secrets.MAIN_FLASK_CONFIG }}" 
          echo "FLATPAGES_AUTO_RELOAD=${{ secrets.MAIN_FLATPAGES_AUTO_RELOAD }}" 
          echo "FLATPAGES_EXTENSION=${{ secrets.MAIN_FLATPAGES_EXTENSION }}" 
          echo "FLATPAGES_ROOT=${{ secrets.MAIN_FLATPAGES_ROOT }}" 
          echo "DIR_BLOG_POSTS=${{ secrets.MAIN_DIR_BLOG_POSTS }}" 
          echo "DIR_PROJECTS=${{ secrets.MAIN_DIR_PROJECTS }}" 
          echo "DIR_TESTIMONIALS=${{ secrets.MAIN_DIR_TESTIMONIALS }}" 
          echo "DIR_TRAININGS=${{ secrets.MAIN_DIR_TRAININGS }}" 
          echo "FLASK_CONFIG=${{ secrets.MAIN_FLASK_CONFIG }}" 
          echo "FLATPAGES_AUTO_RELOAD=${{ secrets.MAIN_FLATPAGES_AUTO_RELOAD }}" 
         

      - name: Run tests 
        env: 
          GITHUB_URL : ${{ secrets.MAIN_GITHUB_URL }} 
          MEDIUM_URL : ${{ secrets.MAIN_MEDIUM_URL }}
          LINKEDIN_URL : ${{ secrets.MAIN_LINKEDIN_URL }} 
          TWITTER_URL : ${{ secrets.MAIN_TWITTER_URL }} 
          SECRET_KEY : ${{ secrets.MAIN_SECRET_KEY }}
          SQLALCHEMY_TRACK_MODIFICATIONS : ${{ secrets.MAIN_SQLALCHEMY_TRACK_MODIFICATIONS }}
          FLASK_CONFIG : ${{ secrets.MAIN_FLASK_CONFIG }}
          FLATPAGES_AUTO_RELOAD : ${{ secrets.MAIN_FLATPAGES_AUTO_RELOAD }} 
          FLATPAGES_EXTENSION : ${{ secrets.MAIN_FLATPAGES_EXTENSION }}
          FLATPAGES_ROOT : ${{ secrets.MAIN_FLATPAGES_ROOT }}
          DIR_BLOG_POSTS : ${{ secrets.MAIN_DIR_BLOG_POSTS }}
          DIR_PROJECTS :  ${{ secrets.MAIN_DIR_PROJECTS }} 
          DIR_TESTIMONIALS : ${{ secrets.MAIN_DIR_TESTIMONIALS }}
          DIR_TRAININGS : ${{ secrets.MAIN_DIR_TRAININGS }} 
          FLASK_DEBUG : 1
         
          
        run: | 
          python -m unittest discover

      - name: Install sshpass 
        run: | 
          sudo apt-get update 
          sudo apt-get install -y sshpass

      - name: Add known hosts entry
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ssh.pythonanywhere.com >> ~/.ssh/known_hosts


      - name: env setup
        run: |
          export USERNAME=${{ secrets.PYTHONANYWHERE_USERNAME }}
          export API_TOKEN=${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          export GTHUB_TOKEN=${{ secrets.GTHUB_TOKEN }}
   

      
      - name: Deploy to PythonAnywhere  
        env:
          PYTHONANYWHERE_SSH_PASSWORD: ${{ secrets.PYTHONANYWHERE_SSH_PASSWORD }}
          GTHUB_TOKEN: ${{ secrets.GTHUB_TOKEN }}
        run: |
          sshpass -p ${{ secrets.PYTHONANYWHERE_SSH_PASSWORD }} ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no -v ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com 'bash ~/deploy.sh'
