name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests 
        run: | 
          python -m unittest discover

      - name: Install sshpass 
        run: | 
          sudo apt-get update 
          sudo apt-get install -y sshpass

      - name: Add known hosts entry
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ssh.pythonanywhere.com >> ~/.ssh/known_hosts


      - name: env setup
        run: |
          export USERNAME=${{ secrets.PYTHONANYWHERE_USERNAME }}
          export API_TOKEN=${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          export GTHUB_TOKEN=${{ secrets.GTHUB_TOKEN }}
   

      
      - name: Deploy to PythonAnywhere  
        env:
          PYTHONANYWHERE_SSH_PASSWORD: ${{ secrets.PYTHONANYWHERE_SSH_PASSWORD }}
          GTHUB_TOKEN: ${{ secrets.GTHUB_TOKEN }}
        run: |
          sshpass -p ${{ secrets.PYTHONANYWHERE_SSH_PASSWORD }} ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no -v ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com 'bash ~/deploy.sh'
